export const GET_USER = 'GET_USER';
export const LOGIN_USER = 'LOGIN_USER';

export const GET_LIST_MOVIES = 'GET_LIST_MOVIES';
export const GET_LIST_RATINGS = 'GET_LIST_RATINGS';

export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';

export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const UNSET_NOTIFICATION = 'UNSET_NOTIFICATION';

export const CHECK_IDENTITY = 'CHECK_IDENTITY';

export const SET_CONTENT_VIEW = 'SET_CONTENT_VIEW';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SHARE_MOVIE = 'SHARE_MOVIE';

export const FETCH_RATINGS = 'FETCH_RATINGS';
export const VOTE_MOVIE = 'VOTE_MOVIE';
